チャレンジのデザイン修正
Yuya-Furusawa/quest-web-cli pull request #4
Opened 2023-07-23 07:14 UTC by t13hayashi

2023-07-23 07:32 UTC, t13hayashi commented on tailwind.config.cjs
> +    require('@tailwindcss/line-clamp'),
サイズはこんな感じそうでした
![image](https://github.com/Yuya-Furusawa/quest-web-cli/assets/26428813/b579e4bd-df83-43eb-9153-18cf62123702)

2023-07-23 14:42 UTC, Yuya-Furusawa commented on package.json
> +    "@tailwindcss/line-clamp": "^0.4.4",
tailwindのline-clampって知らなかった！ナイスです！

2023-07-23 14:45 UTC, Yuya-Furusawa commented on src/pages/QuestPage.tsx
> -        <Spacer size="10px" />
これ消したかった！ありがとうございます🙏

2023-07-29 04:08 UTC, Yuya-Furusawa requested changes
お願いします！🙏

2023-07-29 04:08 UTC, Yuya-Furusawa commented on src/components/Quest/ChallengeCard.tsx
> +          (challenge.id[0].toUpperCase() <= "M" ? "" : "grayscale") // TODO: サーバーから返される完了ステータスに置き換える
Challenge達成/未達成の判定はこのコンポーネント行うのではなくて、`isCompleted`みたいなpropsを渡したほうがいいかも！
このコンポーネント単純に、チャレンジの情報と達成/未達成の情報を受け取って、それを元に表示する感じがいいかもシンプルで良い！（Viewを作るだけでロジックを持たないコンポーネントにする）
そうすると`alt`の条件分岐もしやすいかも

こんな感じのイメージ
```tsx
type Props = {
  challenge: Challenge;
  isCompleted: boolean;
};

const ChallengeCard: React.FC<Props> = React.memo(({ challenge, isCompleted }) => (
  // ...
)
```

2023-07-29 04:08 UTC, Yuya-Furusawa commented on src/components/Quest/ChallengeCard.tsx
> +          (challenge.id[0].toUpperCase() <= "M" ? "" : "grayscale") // TODO: サーバーから返される完了ステータスに置き換える
Propsを変更したらStorybookの方（`ChallengeCard.stories.tsx`）も修正してほしいです！（おそらくエラーがでる）

Storybookに関しては僕がTANPで書いた記事（を元に書き直したZennの記事）とかを参考にしてもらえると！
https://zenn.dev/fullyou/articles/853b77a3ce9144

2023-07-29 07:05 UTC, t13hayashi commented on src/components/Quest/ChallengeCard.tsx
> +          (challenge.id[0].toUpperCase() <= "M" ? "" : "grayscale") // TODO: サーバーから返される完了ステータスに置き換える
ありがとうございます、修正しました:pray:

- Propsで渡すよう修正
    - https://github.com/Yuya-Furusawa/quest-web-cli/pull/4/commits/d76a9c7cb149385a6e7a7af9f84ce3a8554f4eb0
- Storybookの修正
    - https://github.com/Yuya-Furusawa/quest-web-cli/pull/4/commits/7c1ecf9a672552322e62f9e84feb0ba51a255640

| Completed | Not Completed |
| --- | --- |
| <img width="1038" alt="image" src="https://github.com/Yuya-Furusawa/quest-web-cli/assets/26428813/f3f8900b-3ee7-45e5-9831-2633b16d1f14"> | <img width="1017" alt="image" src="https://github.com/Yuya-Furusawa/quest-web-cli/assets/26428813/37f1857e-c173-4fa0-9cc1-6b94aa76acde"> |

2023-07-29 07:54 UTC, Yuya-Furusawa commented on src/components/Quest/ChallengeCard.tsx
> +          (challenge.id[0].toUpperCase() <= "M" ? "" : "grayscale") // TODO: サーバーから返される完了ステータスに置き換える
ナイスです！ありがとう！

2023-07-29 07:56 UTC, Yuya-Furusawa approved these changes
![LGTM](https://images.lgtmgen.org/a3ad4bb5-33d4-46b2-a7be-32ad3a76f26c)

2023-07-29 07:56 UTC, merged